#!/bin/bash

# FILE=$1
NAME=$1
shift
EXTRA=$@



# if [ "$NAME" == "$FILE" ]; then
#     FILE="${FILE}.cpp"
# fi
FILE="cbp.cpp"
COMPILE="g++ -std=c++20"
OPT="-O3"
FLAGS="-Wall -Wextra -pedantic -Wold-style-cast  -Wno-deprecated-declarations -Wno-mismatched-tags"

set -x

$COMPILE -o $NAME $FILE -lz -lsqlite3 $OPT $FLAGS $EXTRA
